### ISSUE TITLE
Segmentation fault on Linux server

### ISSUE THREAD

**Issue by moises-silva** [synergy/synergy#4844]
I am on synergy 1.7.3

This morning I plugged my mac to my docking station and noticed synergy did not connect to the Linux server. The client kept trying unsuccessfully. I went to check the status of the synergy server (in a Fedora 19 Linux box) which I was running in the foreground in a screen session. The server was stopped by a segmentation fault. Here are the last log lines:

https://gist.github.com/moises-silva/ba33816d2e9e8f692742

Here is the backtrace:

https://gist.github.com/moises-silva/a4cde8982eecebb74e3b

Let me know if you need any other information.

**Comment by nbolton** [comment]
It looks like this the cause:
```
#0  0x00000039abc5d14a in __dynamic_cast () from /lib64/libstdc++.so.6
#1  0x0000000000486a52 in ClientListener::handleUnknownClient(Event const&, void*) ()
```

Do you have SSL enabled?

**Comment by moises-silva** [comment]
@nbolton yes I have SSL enabled. The reason I was running it in the foreground is because this new release of synergy has been disconnecting or hanging often (sometimes as often as twice during the work day). I have not seen the core dump again though.
