### ISSUE TITLE
'hm package win' not building Windows installer

### ISSUE THREAD

**Issue by admrply** [synergy/synergy#5052]
`hm conf -g1` and `hm build` finish successfully, but when I run `hm package win` it fails with a Python error 2, file not found.

I ran the command again with a verbose flag and was able to pull out the following error, but I'm still unsure what file it is trying to find?

    [...]
        9 Warning(s)
        0 Error(s)

    Time Elapsed 00:00:04.20
        Traceback (most recent call last):
      File "hm.py", line 24, in <module>
        tc.run(sys.argv)
      File "ext\toolchain\commands1.py", line 196, in run
        self.start_cmd(argv)
      File "ext\toolchain\commands1.py", line 132, in start_cmd
        self.run_cmd(cmd, argv[2:])
      File "ext\toolchain\commands1.py", line 178, in run_cmd
        cmd_func()
      File "ext\toolchain\commands1.py", line 1959, in dist
        self.ic.dist(type, self.vcRedistDir, self.qtDir)
      File "ext\toolchain\commands1.py", line 1056, in dist
        self.distWix()
      File "ext\toolchain\commands1.py", line 1310, in distWix
        self.getVersionForFilename(),
      File "ext\toolchain\commands1.py", line 1386, in getVersionForFilename
        gitBranch = self.getGitBranchName()
      File "ext\toolchain\commands1.py", line 978, in getGitBranchName
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "C:\Python27\lib\subprocess.py", line 710, in __init__
        errread, errwrite)
      File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified

I tried to look through some of the source code, but I'll be honest, I'm not entirely sure what I'm looking for!

**Comment by XinyuHou** [comment]
@admrply 
Please use our dev mailing list to discuss this problem.

https://groups.google.com/forum/?pli=1#!forum/synergy-dev
